### PR TITLE
unbound/run Permissions and newest root.hints

### PR DESCRIPTION
**Pull request by DKeppi**
Change to the correct permissions for unbound/run  and include the newest root.hints to unbound

### CODE REVIEW

**Review by pluim003 — COMMENTED** [review]
I'm not familiar with the root.hints-stuff. Can't find it in the repository of Chris Crowe. I'll need to dig into this. I'll add it to the nightly build though. 
With respect to the permissions: in my container it looks/seems good, but it's good to add of course. Thanx.

**Comment by pluim003** [comment]
Tried your suggestions on my nightly  Dockerfile, but needed some more additions (like useradd unbound).

**Comment by DKeppi** [comment]
Nice to see that you also merged this one!
The root.hints includes the global root servers for the DNS, so with every new image creation you got the actual and trusted list for unbound.

**Comment by DKeppi** [comment]
I forget something...there is an option in unbound-pihole.conf to activate the downloaded root.hints

**Comment by pluim003** [comment]
I’ll take a look at it tomorrow. ThanxOp 27 sep. 2022 om 23:02 heeft DKeppi ***@***.***> het volgende geschreven:﻿
I forget something...there is an option in unbound-pihole.conf to activate the downloaded root.hints

**Pull request merged**
